kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: inferno
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 80
        hostPort: 8080
        protocol: TCP

    extraMounts:
      - hostPath: /dev
        containerPath: /dev

containerdConfigPatches:
  - |
    [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.nvidia]
      runtime_type = "io.containerd.runc.v2"
      [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.nvidia.options]
        Runtime = "nvidia"