apiVersion: apps/v1
kind: Deployment
metadata:
  name: qwen2-5-vl-7b-vllm
  labels:
    app: qwen2-5-vl-7b-vllm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qwen2-5-vl-7b-vllm
  template:
    metadata:
      labels:
        app: qwen2-5-vl-7b-vllm
    spec:
      containers:
        - name: vllm
          image: vllm/vllm-openai:latest
          args:
            - "--model"
            - "Qwen/Qwen2.5-VL-7B-Instruct"
            - "--disable-log-requests"
          env:
            - name: HUGGING_FACE_HUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: hf-credentials
                  key: HUGGING_FACE_HUB_TOKEN
          ports:
            - containerPort: 8000
          resources:
            limits:
              nvidia.com/mig-4g.40gb: 1
          volumeMounts:
            - name: hf-cache
              mountPath: /root/.cache/huggingface
      volumes:
        - name: hf-cache
          hostPath:
            path: /home/ubuntu/.cache/huggingface

---
# -------------------------------------------------
# Service: Stable DNS name inside the cluster
# -------------------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: qwen2-5-vl-7b
spec:
  selector:
    app: qwen2-5-vl-7b-vllm
  ports:
    - port: 8000
      targetPort: 8000