apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-gateway
  template:
    metadata:
      labels:
        app: fastapi-gateway
    spec:
      containers:
        - name: gateway
          image: fastapi-gateway:local
          imagePullPolicy: Never
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-gateway
spec:
  selector:
    app: fastapi-gateway
  ports:
    - port: 80
      targetPort: 80